### PR TITLE
Add type definitions for TypeScript

### PR DESCRIPTION
**Pull request by dora1998**
To use your library in TypeScript, I wrote type definitions.

If you prefer providing this from `@types/*` package to including it in your repository, please tell me.

### CODE REVIEW

**Comment by p1ass** [comment]
Any updates?

**Comment by alexjoverm** [comment]
Maybe this needs now some rework because since v2.0.0 you can find `index.js` for Vue 3 and `index-v2.js` for Vue 2. What do you think @dora1998 ?

**Comment by zynth17** [comment]
any update on this?

**Comment by afif-hh** [comment]
still waiting for this...

**Comment by dora1998** [comment]
@alexjoverm
Sorry for my rate reply. I took a look at changes, then I think it is easier to rewrite code using TS than to add type declaration file.
If you hope so, I'll close this and send another PR. What's your take on this?

**Pull request closed without merging**
